@startuml
:Main Admin: as Admin
(Use the application) as (Use)

User -> (Start)
User --> (Use)

Admin ---> (Use)

note right of Admin : This is Group3.


note right of (Use)
A note can also
be on several lines
end note

note "This note is connected\nto several objects." as N2
(Start) .. N2
N2 .. (Use)
@enduml



@startuml

actor HR as "HR Advisor"

rectangle Database

rectangle "HR System" {
    usecase UC4 as "Get salaries
    by role"

    usecase UCa as "Print salaries"

    HR - UC4
    UC4 ..> UCa : include
    UC4 - Database
}

@enduml

@startuml

usecase "Use Case"

usecase UC1 as "Use Case 1"
usecase UC2 as "Use Case 2"

actor "Actor"

actor A1 as "Actor 1"
actor A2 as "Actor 2"

actor A1 as "Actor 1"
usecase UC1 as "Use Case 1"

A1 --> UC1

rectangle Database

rectangle System {
    usecase UC1 as "Use Case 1"
    UC1 --> Database
}
@enduml